### ISSUE TITLE
Resizing window in MacOS fails to recreate swap chain

### ISSUE THREAD

**Issue by natevm** [n8vm/Pluto#11]
I get the following message after repeatedly recreating a swap chain:

libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument

I can get a stack trace using lldb. Here's what I get:
* thread #6, queue = 'com.Metal.CompletionQueueDispatch', stop reason = signal SIGABRT
  * frame #0: 0x00007fff59b7e23e libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff59c34c1c libsystem_pthread.dylib`pthread_kill + 285
    frame #2: 0x00007fff59ae71c9 libsystem_c.dylib`abort + 127
    frame #3: 0x00007fff57167231 libc++abi.dylib`abort_message + 231
    frame #4: 0x00007fff571673b5 libc++abi.dylib`default_terminate_handler() + 241
    frame #5: 0x00007fff58972c8f libobjc.A.dylib`_objc_terminate() + 105
    frame #6: 0x00007fff57172dfe libc++abi.dylib`std::__terminate(void (*)()) + 8
    frame #7: 0x00007fff57172e73 libc++abi.dylib`std::terminate() + 51
    frame #8: 0x00007fff58972a82 libobjc.A.dylib`objc_terminate + 9
    frame #9: 0x00007fff599f0de3 libdispatch.dylib`_dispatch_client_callout + 28
    frame #10: 0x00007fff599f35dc libdispatch.dylib`_dispatch_continuation_pop + 427
    frame #11: 0x00007fff59a028ed libdispatch.dylib`_dispatch_source_invoke + 2013
    frame #12: 0x00007fff599f6fc9 libdispatch.dylib`_dispatch_lane_serial_drain + 271
    frame #13: 0x00007fff599f7bdc libdispatch.dylib`_dispatch_lane_invoke + 388
    frame #14: 0x00007fff59a00090 libdispatch.dylib`_dispatch_workloop_worker_thread + 603
    frame #15: 0x00007fff59c3160b libsystem_pthread.dylib`_pthread_wqthread + 409
    frame #16: 0x00007fff59c31405 libsystem_pthread.dylib`start_wqthread + 13

**Comment by natevm** [comment]
I was able to solve this on another mac by flushing graphics and present queues before recreating a swapchain. Testing on another mac before closing.

**Comment by cyanpelican** [comment]
Tested on my Mac and the changes seem to work. Used both the resize command from python as well as resizing the window through the mouse.
