### ISSUE TITLE
GLFW cocoa window angry

### ISSUE THREAD

**Issue by cyanpelican** [n8vm/Pluto#2]
A small patch is in external/glfw-patch.txt, but not applied upstream.

Only effects macOS.

**Comment by natevm** [comment]
@cyanpelican Do you remember how you applied this patch? It doesn't seem to work on another Mac I just tried building on.

**Comment by cyanpelican** [comment]
I think it was:

cd into the glfw folder
git apply ../glfw-patch.txt

**Comment by natevm** [comment]
GLFW recently closed their issue which required this patch. Submodule is now updated, and the patch is no longer needed.
