### ISSUE TITLE
Allows most of the build in 32-bit (maybe?) on win10 but fails on Vulkan

### ISSUE THREAD

**Issue by cyanpelican** [n8vm/Pluto#36]
Repro: try running this on win10 git-bash

```
cmake -DCMAKE_BUILD_TYPE=Release ../
cmake --build . --target install --config Release
```

Failure is fairly quiet and not obvious to resolve

Correct version that doesn't die:
```
cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release ../
cmake --build . --target install --config Release
```

**Comment by natevm** [comment]
32 bit builds are currently unsupported. Still, it's not immediately obvious that they are not.

This particular build error was related to a required vk::PhysicalDevice handle cast to an OpenVR function. That's been fixed and pushed to development. Still, we'll get linker errors later on stating "cannot open input file 'openvr_api64.lib', and possibly later on, linker error messages for other dependencies like Python.

I guess we could go two ways with this. We could first try to add support for 32 bit builds. The second is that we could try to prevent cmake from generating 32 bit builds.

**Comment by natevm** [comment]
If we need explicit support for 32 bit platforms, we can make an issue for that. In the mean time, there shouldn't be any build errors related to Vulkan now, just linker errors complaining about 64/32 bit mismatch stuff. That should be an easier error message to fix.

**Comment by cyanpelican** [comment]
Is there a simple way to add an extra error condition to the cmake script when trying to build 32-bit and be a bit more verbose about what’s going wrong?

-
Kevin

**Comment by natevm** [comment]
I wonder if this would work:
https://stackoverflow.com/questions/39258250/how-to-detect-if-64-bit-msvc-with-cmake

**Comment by natevm** [comment]
That seems to work on windows. Now we throw an error message if generating CMake in a 32 bit configuration. It should work on other platforms too.
