### ISSUE TITLE
Race condition for BRDF

### ISSUE THREAD

**Issue by cyanpelican** [n8vm/Pluto#5]
Some race condition in BRDF lut loading and causes periodic (rare) crashes. Reproduced once on macOS.

**Comment by natevm** [comment]
Issue solved by checking to see whether the BRDF texture was loaded before rendering. Fix is in development, and will be merged into master soon.

**Comment by natevm** [comment]
I believe I fixed this bug, so I'm tentatively closing. If we run into the same problem again, we can reopen this issue.
